### ISSUE TITLE
Pre-trained Model for Unconstrained Face Detection

### ISSUE THREAD

**Issue by hector246288** [CitrusRokid/OpenNPD#4]
Hi there, 
Have you ever trained a model for unconstrained face detection?
I have only found one for frontal face detection....

**Comment by cmxnono** [comment]
How do you try the detection script, for example:
> sh script/test_detect_demo.sh

You can put more information about your testing.

**Comment by hector246288** [comment]
I mean the model frontal_face_detector.bin works quite well on the frontal faces.
However, when the face angle becomes greater than 30, the detector has a bad performance....

**Comment by CitrusRokid** [comment]
You can train your own model, "frontal_face_detector.bin" is just a example.
