### ISSUE TITLE
Matlab version models and OpenNPD

### ISSUE THREAD

**Issue by accensi** [CitrusRokid/OpenNPD#6]
Models from Matlab are compatible or can be converted to OpenNPD models?

Thanks

**Comment by cmxnono** [comment]
close all; clear; clc;
 
 modelFile = '../models/model_frontal.mat';
 cModelFile = '../models/model_frontal.bin';
 
 load(modelFile, 'npdModel');
 
 fp = fopen(cModelFile, 'w');
 
 tic;
 
 objSize = npdModel.objSize;
 numStages = npdModel.numStages;
 numBranchNodes = npdModel.numBranchNodes;
 numLeafNodes = npdModel.numLeafNodes;
 scaleFactor = npdModel.scaleFactor;
 numScales = npdModel.numScales;
 
 % stageThreshold float32 numStages x 1
 fwrite(fp, npdModel.stageThreshold, 'float32');
 
 % treeRoot int32 numStages x 1
 fwrite(fp, npdModel.treeRoot, 'int32');
 
 % pixel1 int32 numBranchNodes x numScales
 fwrite(fp, npdModel.pixel1, 'int32');
 
 % pixel2 int32 numBranchNodes x numScales
 fwrite(fp, npdModel.pixel2, 'int32');
 
 % cutpoint uint8 numBranchNodes x 2
 fwrite(fp, npdModel.cutpoint, 'uint8');
 
 % leftChild int32 numBranchNodes x 1
 fwrite(fp, npdModel.leftChild, 'int32');
 
 % rightChild int32 numBranchNodes x 1
 fwrite(fp, npdModel.rightChild, 'int32');
 
 % fit float32 numLeafNodes x 1
 fwrite(fp, npdModel.fit, 'float32');
 
 % winSize int32 1 x numScales
 fwrite(fp, npdModel.winSize, 'int32');
 
 fclose(fp);
 toc; `

**Comment by cmxnono** [comment]
This is my converting code, you can try to yourself's!
